# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
dist: trusty
cache: packages
  
# Be strict when checking our package
warnings_are_errors: false

# nloptr R package requires libnlopt-dev to be installed, which requires trusty ubuntu
# phantomjs required for shinytest for VEGUI testing
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnlopt-dev
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "hash -r"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
  - "phantomjs --version"

install:
  - Rscript -e 'install.packages(c("curl","devtools", "roxygen2", "stringr", "knitr", "data.table", "ordinal", "geosphere", "fields", "car", "pbkrtest", "quantreg", "reshape"))'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'
  # Packages required for VEGUI  
  - Rscript -e 'install.packages(c("shiny", "shinyjs", "shinyFiles", "data.table", "DT", "shinyBS", "future", "testit", "jsonlite", "shinyAce", "envDocument", "rhandsontable", "shinyTree"))'
  - Rscript -e 'devtools::install_github(c("tdhock/namedCapture", "rstudio/webdriver", "rstudio/shinytest"))'

# setup a different environment variable for each Travis build environment (in the matrix) to run in parallel
  
before_script:
  - Rscript -e 'print(.libPaths())'
  - Rscript -e 'print(installed.packages())'

# install and test framework, modules, models, GUI
script:
  - |
    ECHO CACHE_NAME
    #install framework
    cd sources/framework/visioneval
    Rscript -e 'devtools::install_deps(".")'
    R CMD INSTALL .
    cd ../../..
    
    #install dependent packages
    IFS=',' read -r -a packages <<< $DEPENDS
    for element in ${packages[@]}
    do
      if ( [ $element != "." ] ); then
        cd sources/modules/$element
        Rscript -e 'devtools::install_deps(".")'
        R CMD INSTALL .
        cd ../../..
      fi
    done
    
    #run module or model tests
    cd $FOLDER
    if ( [ $TYPE == "module" ] ); then
      Rscript -e 'devtools::install_deps(".")'
      Rscript -e 'devtools::check(".")'
      Rscript -e "tryCatch( source( '$SCRIPT' ) )"
      R CMD INSTALL .
      exit_status=$?
    else
      Rscript -e "tryCatch( source( '$SCRIPT' ) )"
      exit_status=$?
    fi
    exit $exit_status
